<x-admin-layout>
    <x-slot name="title">Dashboard</x-slot>


    <div class="position-relative fs-2x z-index-2 fw-bolder mb-7">
        <span class="me-2">Welcome Back
            <span class="position-relative d-inline-block text-danger">
                <a href="#" class="text-dark opacity-75-hover"> {{ auth()->user()->name }} </a>
                <span
                    class="position-absolute opacity-50 bottom-0 start-0 border-4 border-dark border-bottom w-100"></span>
            </span></span>
    </div>




    @role(\App\Enums\User\RoleEnum::ADMIN)
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body p-0">
                        <div class="d-flex  p-4">
                            <div class="d-flex align-items-center flex-grow-1 me-2 me-sm-5">
                                <div class="symbol symbol-50px me-4">
                                    <span class="symbol-label">
                                        <span class="svg-icon svg-icon-2qx svg-icon-dark">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="25"
                                                viewBox="0 0 24 25" fill="none">
                                                <path opacity="0.3"
                                                    d="M8.9 21L7.19999 22.6999C6.79999 23.0999 6.2 23.0999 5.8 22.6999L4.1 21H8.9ZM4 16.0999L2.3 17.8C1.9 18.2 1.9 18.7999 2.3 19.1999L4 20.9V16.0999ZM19.3 9.1999L15.8 5.6999C15.4 5.2999 14.8 5.2999 14.4 5.6999L9 11.0999V21L19.3 10.6999C19.7 10.2999 19.7 9.5999 19.3 9.1999Z"
                                                    fill="currentColor" />
                                                <path
                                                    d="M21 15V20C21 20.6 20.6 21 20 21H11.8L18.8 14H20C20.6 14 21 14.4 21 15ZM10 21V4C10 3.4 9.6 3 9 3H4C3.4 3 3 3.4 3 4V21C3 21.6 3.4 22 4 22H9C9.6 22 10 21.6 10 21ZM7.5 18.5C7.5 19.1 7.1 19.5 6.5 19.5C5.9 19.5 5.5 19.1 5.5 18.5C5.5 17.9 5.9 17.5 6.5 17.5C7.1 17.5 7.5 17.9 7.5 18.5Z"
                                                    fill="currentColor" />
                                            </svg>
                                        </span>
                                    </span>
                                </div>
                                <div class="me-2">
                                    <a href="#" class="text-gray-800 text-hover-primary fs-6 fw-bolder">Tickets</a>
                                    <span class="text-gray-400 fw-bolder d-block fs-7">Support Tickets Generated by the Staff</span>
                                </div>
                            </div>

                            <div class="d-flex align-items-center">
                                <span class="text-dark fw-boldest fs-2x">{{ $tickets_open }}</span>
                                <span class="fw-bold fs-2 text-gray-600 mx-1 pt-1">/</span>
                                <span class="text-gray-600 fw-bold fs-2 me-3 pt-2">{{ $tickets }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-6">

                <div class="card shadow">
                    <div class="card-body p-4">
                        <canvas id="tickets_chart" class="mh-200px"></canvas>
                    </div>
                </div>

            </div>

        </div>

        <x-slot:scripts>
            <script>
                var ctx = document.getElementById('tickets_chart');

                // Define colors 
                var dangerColor = KTUtil.getCssVariableValue('--bs-danger');
                var successColor = KTUtil.getCssVariableValue('--bs-success');

                // Define fonts
                var fontFamily = KTUtil.getCssVariableValue('--bs-font-sans-serif');

                // Chart labels
                const labels = ['Open', 'Closed'];

                // Chart data
                const data = {
                    labels: labels,
                    datasets: [{
                        label: "Tickets",
                        data: [{{ $tickets_open }}, {{ $tickets - $tickets_open }}],
                        backgroundColor: [successColor, dangerColor]
                    }]
                };

                // Chart config
                const config = {
                    type: 'pie',
                    data: data,
                    options: {
                        plugins: {
                            title: {
                                display: false,
                            }
                        },
                        responsive: true,
                    },
                    defaults: {
                        global: {
                            defaultFont: fontFamily
                        }
                    }
                };

                var myChart = new Chart(ctx, config);
            </script>
        </x-slot:scripts>
    @endrole

</x-admin-layout>
